[book]
authors = ["Damien Elmes"]
language = "en"
multilingual = false
src = "src"
title = "Frequently Asked Questions"

[build]
create-missing = false

[output.html]
no-section-label = true
git-repository-url = "https://github.com/ankitects/faqs/"

[output.linkcheck]
